### ISSUE TITLE
Scoring is incorrect

### ISSUE THREAD

**Issue by theartful** [yahiaetman/Go-Server#3]
**Describe the bug**
The scoring function is incorrect, it adds erroneous number of captured stones when an agent has passed and the other is still playing. 

**To Reproduce**
1. Make an agent pass
2. Make the other agent play in one of his eyes (or any intersection surrounded by his stones)
3. Watch the number of captured stones go up.

**Expected behavior**
These are not captures, and hence the total score is incorrect.

**Video Evidence**
https://youtu.be/HozIyyecLnY

**Additional context**
Sorry for bringing this up this late, but I hope this can be fixed before the competition.

**Comment by yahiaetman** [comment]
Could you send the log for this game? Thank you.

**Comment by yahiaetman** [comment]
Note that doing a pass will add a stone to the opponent's prisoners.

**Comment by yahiaetman** [comment]
Fixed in c3e45aa57ea2ebe71f6efd33c2c2e0484ab54281
